application: APPLICATION_NAME
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /.*
  script: main.application
  secure: always
